import { z } from "zod";
import { router, protectedProcedure } from "@/lib/trpc/init";

type Goal = "gain_mass" | "lose_weight" | "both";
type MealType = "breakfast" | "lunch" | "dinner" | "snack";

const RECIPES = [
  {
    id: "rec-001",
    name: "Owsianka z bananem i orzechami",
    description: "Energetyczne śniadanie bogate w węglowodany złożone i zdrowe tłuszcze.",
    calories: 420,
    protein: 14,
    carbs: 62,
    fat: 14,
    mealType: "breakfast" as MealType,
    targetGoal: "gain_mass" as Goal,
    prepMinutes: 10,
    ingredients: ["100g płatki owsiane", "1 banan", "30g orzechy włoskie", "200ml mleko", "1 łyżka miód"],
    steps: ["Ugotuj płatki na mleku", "Pokrój banana w plastry", "Dodaj orzechy i miód", "Wymieszaj i podawaj ciepłe"],
  },
  {
    id: "rec-002",
    name: "Kurczak z ryżem i brokułami",
    description: "Klasyczny posiłek budujący masę mięśniową. Wysoka zawartość białka i węglowodanów.",
    calories: 550,
    protein: 48,
    carbs: 58,
    fat: 8,
    mealType: "lunch" as MealType,
    targetGoal: "gain_mass" as Goal,
    prepMinutes: 25,
    ingredients: ["200g pierś z kurczaka", "150g ryż biały", "200g brokuły", "1 łyżka oliwa", "Sól, pieprz, czosnek"],
    steps: ["Ugotuj ryż", "Ugotuj brokuły na parze", "Usmaż kurczaka na oliwie z czosnkiem", "Podawaj razem"],
  },
  {
    id: "rec-003",
    name: "Sałatka z tuńczykiem",
    description: "Lekki posiłek redukcyjny. Dużo białka, mało kalorii.",
    calories: 280,
    protein: 32,
    carbs: 12,
    fat: 10,
    mealType: "lunch" as MealType,
    targetGoal: "lose_weight" as Goal,
    prepMinutes: 10,
    ingredients: ["1 puszka tuńczyk w sosie własnym", "Mix sałat 100g", "1 pomidor", "0.5 ogórek", "1 łyżka oliwa", "Sok z cytryny"],
    steps: ["Odsącz tuńczyka", "Pokrój warzywa", "Wymieszaj z sałatą", "Skrop oliwą i cytryną"],
  },
  {
    id: "rec-004",
    name: "Jajecznica z warzywami",
    description: "Szybkie, białkowe śniadanie niskokaloryczne.",
    calories: 320,
    protein: 22,
    carbs: 8,
    fat: 22,
    mealType: "breakfast" as MealType,
    targetGoal: "lose_weight" as Goal,
    prepMinutes: 10,
    ingredients: ["3 jajka", "1 papryka czerwona", "0.5 cebula", "1 łyżka masło", "Sól, pieprz, szczypiorek"],
    steps: ["Podsmaż cebulę z papryką na maśle", "Wbij jajka i mieszaj", "Dopraw solą i pieprzem", "Posyp szczypiorkiem"],
  },
  {
    id: "rec-005",
    name: "Shake białkowy z owocami",
    description: "Idealna przekąska potreningowa wspierająca regenerację.",
    calories: 380,
    protein: 35,
    carbs: 44,
    fat: 6,
    mealType: "snack" as MealType,
    targetGoal: "both" as Goal,
    prepMinutes: 5,
    ingredients: ["30g odżywka białkowa waniliowa", "200ml mleko 2%", "100g truskawki mrożone", "0.5 banan", "1 łyżka masło orzechowe"],
    steps: ["Wrzuć wszystkie składniki do blendera", "Blenduj przez 30 sekund", "Podawaj od razu"],
  },
  {
    id: "rec-006",
    name: "Zupa warzywna z soczewicą",
    description: "Sycąca zupa dietetyczna pełna błonnika i roślinnego białka.",
    calories: 290,
    protein: 18,
    carbs: 42,
    fat: 4,
    mealType: "dinner" as MealType,
    targetGoal: "lose_weight" as Goal,
    prepMinutes: 35,
    ingredients: ["150g soczewica czerwona", "2 marchewki", "1 cebula", "2 ząbki czosnku", "1 puszka pomidory", "Kumin, kurkuma, sól"],
    steps: ["Podsmaż cebulę i czosnek", "Dodaj marchewkę i przyprawy", "Dodaj soczewicę i pomidory", "Zalej wodą i gotuj 25 min"],
  },
  {
    id: "rec-007",
    name: "Makaron z mięsem mielonym",
    description: "Treściwy obiad masowy z dużą ilością kalorii i białka.",
    calories: 680,
    protein: 42,
    carbs: 72,
    fat: 22,
    mealType: "dinner" as MealType,
    targetGoal: "gain_mass" as Goal,
    prepMinutes: 30,
    ingredients: ["200g makaron penne", "250g mięso mielone wołowe", "1 puszka passata", "1 cebula", "2 ząbki czosnku", "Oregano, bazylia"],
    steps: ["Ugotuj makaron al dente", "Podsmaż cebulę z czosnkiem", "Dodaj mięso i przesmaż", "Dodaj passatę i gotuj 15 min", "Połącz z makaronem"],
  },
  {
    id: "rec-008",
    name: "Jogurt grecki z granolą",
    description: "Szybka przekąska z żywymi kulturami bakterii i prebiotykami.",
    calories: 310,
    protein: 20,
    carbs: 38,
    fat: 8,
    mealType: "snack" as MealType,
    targetGoal: "both" as Goal,
    prepMinutes: 3,
    ingredients: ["200g jogurt grecki 0%", "40g granola", "1 łyżka miód", "Owoce sezonowe do smaku"],
    steps: ["Przełóż jogurt do miseczki", "Posyp granolą", "Skrop miodem", "Dodaj owoce"],
  },
  {
    id: "rec-009",
    name: "Omlet z warzywami i serem feta",
    description: "Syci na długi czas i dostarcza białka oraz warzyw.",
    calories: 390,
    protein: 25,
    carbs: 10,
    fat: 25,
    mealType: "breakfast" as MealType,
    targetGoal: "both" as Goal,
    prepMinutes: 12,
    ingredients: ["3 jajka", "50g ser feta", "1 pomidor", "1 garść szpinaku", "2 łyżki oliwa", "Sól, pieprz"],
    steps: ["Podsmaż warzywa na oliwie", "Wlej roztrzepane jajka", "Dodaj pokruszoną fetę", "Smaż do ścięcia"],
  },
  {
    id: "rec-010",
    name: "Sałatka quinoa z kurczakiem",
    description: "Lekki, sycący lunch z białkiem i dobrymi tłuszczami.",
    calories: 520,
    protein: 38,
    carbs: 48,
    fat: 18,
    mealType: "lunch" as MealType,
    targetGoal: "both" as Goal,
    prepMinutes: 20,
    ingredients: ["100g quinoa", "150g pierś z kurczaka", "1 awokado", "50g rukola", "1 łyżka oliwa", "Sok z cytryny"],
    steps: ["Ugotuj quinoa", "Usmaż kurczaka", "Wymieszaj z rukolą i awokado", "Skrop oliwą i cytryną"],
  },
  {
    id: "rec-011",
    name: "Koktajl z burakiem i białkiem",
    description: "Szybki napój regeneracyjny o dobrym profilu aminokwasowym.",
    calories: 360,
    protein: 30,
    carbs: 50,
    fat: 6,
    mealType: "snack" as MealType,
    targetGoal: "gain_mass" as Goal,
    prepMinutes: 5,
    ingredients: ["30g odżywka białkowa", "100g gotowany burak", "200ml mleko migdałowe", "1 banan"],
    steps: ["Włóż składniki do blendera", "Blenduj przez 45 sekund", "Przelej do szklanki"],
  },
  {
    id: "rec-012",
    name: "Ciecierzyca curry z ryżem",
    description: "Przepis wegetariański z dobrym balansem węglowodanów i białka.",
    calories: 470,
    protein: 22,
    carbs: 62,
    fat: 14,
    mealType: "dinner" as MealType,
    targetGoal: "lose_weight" as Goal,
    prepMinutes: 30,
    ingredients: ["200g ciecierzyca ugotowana", "1 puszka mleko kokosowe", "1 cebula", "2 ząbki czosnku", "1 łyżka curry", "150g brązowy ryż"],
    steps: ["Podsmaż cebulę i czosnek", "Dodaj curry i ciecierzycę", "Wlej mleko kokosowe i gotuj 15 minut", "Podawaj z ugotowanym ryżem"],
  },
  {
    id: "rec-013",
    name: "Placuszki bananowe z twarogiem",
    description: "Słodkie śniadanie bogate w białko i energię.",
    calories: 390,
    protein: 28,
    carbs: 40,
    fat: 14,
    mealType: "breakfast" as MealType,
    targetGoal: "gain_mass" as Goal,
    prepMinutes: 15,
    ingredients: ["1 banan", "2 jajka", "50g twaróg", "20g mąka pełnoziarnista", "1 łyżeczka cynamon"],
    steps: ["Zblenduj składniki", "Usmaż placuszki na patelni", "Podawaj z owocami"],
  },
  {
    id: "rec-014",
    name: "Owsianka migdałowo-jabłkowa",
    description: "Ciepłe śniadanie wegetariańskie z aromatycznym jabłkiem.",
    calories: 340,
    protein: 12,
    carbs: 56,
    fat: 12,
    mealType: "breakfast" as MealType,
    targetGoal: "lose_weight" as Goal,
    prepMinutes: 10,
    ingredients: ["50g płatki owsiane", "1 jabłko", "200ml mleko migdałowe", "1 łyżeczka miód", "szczypta cynamon"],
    steps: ["Ugotuj płatki z mlekiem", "Dodaj pokrojone jabłko", "Posyp cynamonem"],
  },
  {
    id: "rec-015",
    name: "Jajka po benedyktyńsku z szpinakiem",
    description: "Wykwintne śniadanie z dobrym źródłem białka i warzyw.",
    calories: 410,
    protein: 24,
    carbs: 18,
    fat: 24,
    mealType: "breakfast" as MealType,
    targetGoal: "both" as Goal,
    prepMinutes: 18,
    ingredients: ["2 jajka", "2 plastry pełnoziarnistego chleba", "1 garść szpinaku", "1 łyżka jogurt grecki", "sól, pieprz"],
    steps: ["Podsmaż szpinak", "Ułóż chleb, szpinak i jajko w koszulce", "Podawaj z jogurtem"],
  },
  {
    id: "rec-016",
    name: "Burrito z indykiem",
    description: "Pełnowartościowy lunch z indykiem, fasolą i warzywami.",
    calories: 540,
    protein: 40,
    carbs: 58,
    fat: 16,
    mealType: "lunch" as MealType,
    targetGoal: "gain_mass" as Goal,
    prepMinutes: 25,
    ingredients: ["1 tortilla pełnoziarnista", "150g indyk mielony", "50g fasola czerwona", "1 awokado", "salsą"],
    steps: ["Usmaż indyka z przyprawami", "Podgrzej tortillę", "Złóż burrito z warzywami i awokado"],
  },
  {
    id: "rec-017",
    name: "Sałatka z łososiem i ogórkiem",
    description: "Lekki lunch z omega-3 i świeżymi warzywami.",
    calories: 420,
    protein: 30,
    carbs: 18,
    fat: 24,
    mealType: "lunch" as MealType,
    targetGoal: "both" as Goal,
    prepMinutes: 15,
    ingredients: ["100g wędzony łosoś", "1 ogórek", "sałata", "1 łyżka oliwa", "sok z cytryny"],
    steps: ["Pokrój warzywa", "Wymieszaj składniki", "Skrop oliwą i cytryną"],
  },
  {
    id: "rec-018",
    name: "Wrap z hummusem i kurczakiem",
    description: "Lunch do zabrania, idealny po treningu.",
    calories: 500,
    protein: 36,
    carbs: 50,
    fat: 18,
    mealType: "lunch" as MealType,
    targetGoal: "gain_mass" as Goal,
    prepMinutes: 10,
    ingredients: ["tortilla pełnoziarnista", "50g hummus", "100g kurczak grillowany", "sałata", "pomidor"],
    steps: ["Nałóż hummus na tortillę", "Dodaj kurczaka i warzywa", "Zwiń wrapa"],
  },
  {
    id: "rec-019",
    name: "Miska z kaszą gryczaną i pieczonymi warzywami",
    description: "Pożywny dinner z błonnikiem i roślinnym białkiem.",
    calories: 450,
    protein: 22,
    carbs: 54,
    fat: 16,
    mealType: "dinner" as MealType,
    targetGoal: "lose_weight" as Goal,
    prepMinutes: 35,
    ingredients: ["100g kasza gryczana", "200g mieszanka warzyw", "1 łyżka oliwa", "przyprawy"],
    steps: ["Upiecz warzywa", "Ugotuj kaszę", "Połącz składniki"],
  },
  {
    id: "rec-020",
    name: "Stek z wołowiny z pieczonymi ziemniakami",
    description: "Mocny obiad dla osób, które chcą zwiększyć masę mięśniową.",
    calories: 720,
    protein: 50,
    carbs: 54,
    fat: 34,
    mealType: "dinner" as MealType,
    targetGoal: "gain_mass" as Goal,
    prepMinutes: 35,
    ingredients: ["200g stek wołowy", "200g ziemniaki", "1 łyżka oliwa", "rozmaryn"],
    steps: ["Upiecz ziemniaki", "Usmaż stek", "Podawaj razem"],
  },
  {
    id: "rec-021",
    name: "Makaron z pesto i kurczakiem",
    description: "Pyszny obiad z włoskim akcentem i wysoką zawartością białka.",
    calories: 630,
    protein: 38,
    carbs: 74,
    fat: 20,
    mealType: "dinner" as MealType,
    targetGoal: "both" as Goal,
    prepMinutes: 25,
    ingredients: ["150g makaron pełnoziarnisty", "100g kurczak", "2 łyżki pesto", "parmezan"],
    steps: ["Ugotuj makaron", "Usmaż kurczaka", "Wymieszaj z pesto"],
  },
  {
    id: "rec-022",
    name: "Sałatka z kalafiorem i ciecierzycą",
    description: "Lekki lunch z roślinnym białkiem, idealny przy redukcji.",
    calories: 390,
    protein: 16,
    carbs: 32,
    fat: 20,
    mealType: "lunch" as MealType,
    targetGoal: "lose_weight" as Goal,
    prepMinutes: 20,
    ingredients: ["150g kalafior", "100g ciecierzyca", "garść szpinaku", "2 łyżki oliwa", "sok z cytryny"],
    steps: ["Upiecz kalafior", "Wymieszaj z ciecierzycą i szpinakiem", "Skrop dressingiem"],
  },
  {
    id: "rec-023",
    name: "Koktajl pomarańczowo-marchwiowy",
    description: "Świeży snack z witaminą C i odżywczą bazą białkową.",
    calories: 320,
    protein: 22,
    carbs: 42,
    fat: 8,
    mealType: "snack" as MealType,
    targetGoal: "both" as Goal,
    prepMinutes: 5,
    ingredients: ["1 pomarańcza", "1 marchewka", "30g odżywka białkowa", "200ml woda"],
    steps: ["Blenduj wszystkie składniki", "Podawaj schłodzone"],
  },
  {
    id: "rec-024",
    name: "Tosty z twarożkiem i rzodkiewką",
    description: "Lekka przekąska białkowa na szybki zastrzyk energii.",
    calories: 310,
    protein: 18,
    carbs: 28,
    fat: 14,
    mealType: "snack" as MealType,
    targetGoal: "lose_weight" as Goal,
    prepMinutes: 8,
    ingredients: ["2 kromki chleba pełnoziarnistego", "100g twarożek", "kilka rzodkiewek", "szczypiorek"],
    steps: ["Posmaruj tosty twarożkiem", "Dodaj pokrojoną rzodkiewkę", "Posyp szczypiorkiem"],
  },
  {
    id: "rec-025",
    name: "Budda bowl z fasolą i awokado",
    description: "Śniadanie lub lunch pełne roślinnego białka i zdrowych tłuszczów.",
    calories: 520,
    protein: 24,
    carbs: 48,
    fat: 24,
    mealType: "lunch" as MealType,
    targetGoal: "both" as Goal,
    prepMinutes: 20,
    ingredients: ["100g czerwona fasola", "1 awokado", "1 marchewka", "mix sałat", "1 łyżka tahini"],
    steps: ["Ułóż składniki w misce", "Polaj tahini", "Wymieszaj przed jedzeniem"],
  },
  {
    id: "rec-026",
    name: "Śniadanie z owsianki i masła orzechowego",
    description: "Szybkie śniadanie z dodatkową porcją tłuszczów i białka.",
    calories: 420,
    protein: 18,
    carbs: 46,
    fat: 18,
    mealType: "breakfast" as MealType,
    targetGoal: "gain_mass" as Goal,
    prepMinutes: 8,
    ingredients: ["50g płatki owsiane", "200ml mleko", "1 łyżka masło orzechowe", "1 banan"],
    steps: ["Ugotuj płatki", "Dodaj masło orzechowe i banana", "Wymieszaj"],
  },
  {
    id: "rec-027",
    name: "Koktajl z zielonym jabłkiem i szpinakiem",
    description: "Odżywczy przekąsek dla regeneracji i nawadniania.",
    calories: 330,
    protein: 20,
    carbs: 42,
    fat: 8,
    mealType: "snack" as MealType,
    targetGoal: "lose_weight" as Goal,
    prepMinutes: 5,
    ingredients: ["1 zielone jabłko", "szklanka szpinaku", "30g odżywka białkowa", "200ml woda"],
    steps: ["Blenduj wszystkie składniki", "Podawaj świeże"],
  },
  {
    id: "rec-028",
    name: "Pierś z kurczaka z warzywami na parze",
    description: "Klasyczny obiad redukcyjny z niskim tłuszczem.",
    calories: 410,
    protein: 39,
    carbs: 30,
    fat: 14,
    mealType: "dinner" as MealType,
    targetGoal: "lose_weight" as Goal,
    prepMinutes: 30,
    ingredients: ["150g pierś z kurczaka", "200g mix warzyw", "1 łyżka oliwa", "sól, pieprz"],
    steps: ["Ugotuj warzywa na parze", "Usmaż kurczaka bez tłuszczu", "Podawaj razem"],
  },
  {
    id: "rec-029",
    name: "Tosty z awokado i wędzonym łososiem",
    description: "Wykwintny posiłek na śniadanie z omega-3 i zdrowymi tłuszczami.",
    calories: 430,
    protein: 26,
    carbs: 28,
    fat: 22,
    mealType: "breakfast" as MealType,
    targetGoal: "both" as Goal,
    prepMinutes: 10,
    ingredients: ["2 kromki chleba pełnoziarnistego", "1 awokado", "50g łosoś wędzony", "cytryna"],
    steps: ["Upiecz chleb", "Nałóż awokado i łososia", "Skrop cytryną"],
  },
  {
    id: "rec-030",
    name: "Baton białkowy domowej roboty",
    description: "Przekąska na szybką regenerację po treningu.",
    calories: 380,
    protein: 26,
    carbs: 32,
    fat: 18,
    mealType: "snack" as MealType,
    targetGoal: "gain_mass" as Goal,
    prepMinutes: 10,
    ingredients: ["100g płatki owsiane", "30g białko", "50g masło orzechowe", "1 łyżka miód"],
    steps: ["Wymieszaj składniki", "Uformuj batoniki", "Schłodź w lodówce"],
  },
];

export const dietRouter = router({
  list: protectedProcedure
    .input(
      z.object({
        targetGoal: z.enum(["gain_mass", "lose_weight", "both", "all"]).optional().default("all"),
        mealType: z.enum(["breakfast", "lunch", "dinner", "snack", "all"]).optional().default("all"),
      })
    )
    .query(({ input }) => {
      let results = RECIPES;
      if (input.targetGoal !== "all") {
        results = results.filter(
          (r) => r.targetGoal === input.targetGoal || r.targetGoal === "both"
        );
      }
      if (input.mealType !== "all") {
        results = results.filter((r) => r.mealType === input.mealType);
      }
      return results.map(({ steps: _steps, ingredients: _ing, ...r }) => r);
    }),

  getById: protectedProcedure
    .input(z.object({ id: z.string() }))
    .query(({ input }) => {
      const recipe = RECIPES.find((r) => r.id === input.id);
      if (!recipe) throw new Error("Recipe not found");
      return recipe;
    }),
});
